### ISSUE TITLE
PlaceholderAPI support?

### ISSUE THREAD

**Issue by nitrogenfive** [Niestrat99/ChatPings#1]
Integration with placeholder API would be nice. My server uses a plugin called HexNicks, so I would like to be able to ping people based on their nicknames rather than their usernames if possible :)

**Comment by Niestrat99** [comment]
I've been implementing nickname pinging with Essentials' nickname features before so I'm sure I can try and implement Placeholder API into it too. I cannot say when it'll be done though as life's gotten a little busy recently.

Thanks for the suggestion!

**Comment by Niestrat99** [comment]
Hi again!
Just wanted to let you know that I managed to implement PlaceholderAPI into the plugin. You can now use the "ping.placeholder" option inside the config.yml to specify your placeholder (example '%nicky_nickname%').

After that you simply use /pingreload to reload the config changes or restart the server.

If there's any questions you can simply open a new issue or join the Discord server https://discord.gg/jntpdcM

I wish you a wonderful start into the year!
