### ISSUE TITLE
Vanished Players are still pinged

### ISSUE THREAD

**Issue by the-n1n** [Niestrat99/ChatPings#2]
Vanished Players Via VanishNoPacket and/or Essentialsx are still pinged by non vanished players and the chat message is still highlighted. The ideal solution would involve the Vanished Player not being pinged or the message highlighted. Could be achieved by hooking into Essentials or VanishNoPacket and is auto-disabled when vanished and depending if they toggled on or off to re-enable.

**Comment by Niestrat99** [comment]
Thank you for bringing this to my attention!
I shall try and have that implemented by the end of the week since exams are currently coming in waves.

**Comment by Niestrat99** [comment]
Quick update I decided to write it now.
On top of that it was just a one-liner so it was a very easy solution. I shall release version 2.5 on both Modrinth and SpigotMC for you to download!
