### ISSUE TITLE
/msg with EssentialsX doesnt activate pings

### ISSUE THREAD

**Issue by Jakeplays12** [Niestrat99/ChatPings#4]
I noticed if you run  a command like: `/msg Jakeplays12 @Jakeplays12 Ohi` the ping doesnt get registered

**Comment by Niestrat99** [comment]
I don't think I can do anything about that since /msg is run by another plugin and therefore has a different event firing.

I can take a look at it when possible, but I cannot guarantee to get that fixed due to the reason I just mentioned.
