### ISSUE TITLE
the local chat working ping 

### ISSUE THREAD

**Issue by dscss1** [Niestrat99/ChatPings#6]
i using a chatty i not want ping peopel in local chat

**Comment by Niestrat99** [comment]
So you don't want players to be able to use pings when in local chats.
I'll have to see if the chatty plugin has an API I can work with, because if they don't then I will probably not be able to do anything about it.

I'll keep you updated though.

**Comment by Niestrat99** [comment]
Hi again!
I bring good news: we were able to implement Chatty into the plugin. You can use the latest build here: https://github.com/Niestrat99/ChatPings/actions/runs/8455383100

The way how you can ignore pings in certain chat channels is simple:

1. Open the config file of Chatty and set the **Chat Listener Priority** to "highest".
2. Restart your server for this config change to take effect.
3. Open the config.yml of ChatPings.
4. Look for the **ignored-chats**-setting in the ping section.
5. Remove the square brackets "[]", make a new line and enter "- local".

This is how the config setting will look like then:

```YAML
ping:
  ignored-chats:
  - local
```

6. use /pingreload to reload ChatPings' config.yml file.

That should solve the issue you have. Let me know if it worked!

**Comment by Niestrat99** [comment]
Closing issue as there hasn't been anything else reported, assuming that the problem has been solved.

If you find any more issues, please don't hesitate opening another issue!
